server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://hw.lgypro.com:3306/hotel?useSSL=false
    username: root
    password: d861d7e5-ac5d-4c78-801b-b916a1bb2fe3
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: https://elasticsearch.liguanghui.pro:9200
    apiKey: VC1seVc0NEJRTVVVMG1ScGNCNFg6NTBWS0VjejlSNFdVVnNYREhtNEx0UQ==
    fingerprint: 8C:9B:46:DD:A1:5A:7A:A0:45:72:1B:31:93:C2:0E:32:FA:E0:2E:F4:DE:1B:19:45:44:83:82:97:FE:86:D2:DB
logging:
  level:
    com.lgypro.hotel: debug
    org.apache.http.wire: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lgypro.hotel.pojo
sync:
  enable-consume-hotel-sync-messages: true
  aws:
    sqs:
      region-id: ap-northeast-1
      queue-name: hotel-sync