server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://hw.lgypro.com:3306/hotel?useSSL=false
    username: root
    password: d861d7e5-ac5d-4c78-801b-b916a1bb2fe3
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.lgypro.hotel: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lgypro.hotel.pojo
sync:
  enable-produce-hotel-sync-messages: true
  aws:
    sqs:
      region-id: ap-northeast-1
      queue-name: hotel-sync
